version: "3"

services:
  reverse_proxy:
    build: reverse_proxy
    container_name: reverse_proxy
    hostname: reverse_proxy
    networks:
      - frontend
    depends_on:
      - maintenance
    volumes:
    #  - ./reverse_proxy/html:/usr/share/nginx/html
      - ./reverse_proxy/conf.d:/etc/nginx/conf.d
      - certs:/etc/pki/tls
    ports:
      - "8080:80"
      - "8443:443"

volumes:
  certs:
    external: true

networks:
  default:
    external:
      name: applink
  frontend:
    external:
      name: appfront
  backend:
    external:
      name: appback
