version: "3"

services:
  maintenance:
    build: maintenance
    container_name: maintenance
    hostname: maintenance
    networks:
      - frontend
    volumes:
      - ./maintenance/html:/usr/share/nginx/html


networks:
  default:
    external:
      name: applink
  frontend:
    external:
      name: appfront
  backend:
    external:
      name: appback
