version: "3"

services:
  app-server:
    build: ${ROOTDIR}/app_server
    container_name: app-server
    hostname: app-server
    networks:
      - frontend
      - backend
    volumes:
      - ${ROOTDIR}:/go/src/github.com/ignite
    working_dir: /go/src/github.com/ignite/app
    command: >
      go run main.go

networks:
  default:
    external:
      name: applink
  frontend:
    external:
      name: appfront
  backend:
    external:
      name: appback
